"use client";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Sidebar } from "@/components/sidebar";
import { useEffect } from "react";
import { useAuth } from "@/hooks/useAuth";

const inter = Montserrat({ subsets: ["latin", "cyrillic"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const setUser = useAuth((state) => state.setUser);
  useEffect(() => {
    const userInfo = fetch(`${process.env.NEXT_PUBLIC_API_URL}/auth/info`, {
      credentials: "include",
    })
      .then((resp) => {
        if (resp.status === 200) {
          return resp.json();
        } else {
          return null;
        }
      })
      .then((info) => {
        if (!info) {
          setUser(null);
        } else {
          setUser({
            email: `${info.email}`,
            firstName: `${info.given_name}`,
            lastName: `${info.family_name}`,
            picture: `${info.picture}`,
          });
        }
      });
  }, []);
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        <div className="flex min-h-[100vh] bg-black">
          <Sidebar />
          <main className="bg-darkGrey flex flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
