"use client";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Sidebar } from "@/components/sidebar";
import { useAuth } from "@/hooks/useAuth";

const inter = Montserrat({ subsets: ["latin", "cyrillic"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const setUser = useAuth((state) => state.setUser);
  const getUser = async () => {
    const response = await fetch(
      `${process.env.NEXT_PUBLIC_API_URL}/auth/info`,
      {
        credentials: "include",
      }
    );

    const userInfo = await response.json();
    if (userInfo?.statusCode === 401) {
      setUser(null);
    } else {
      setUser({
        email: userInfo.email,
        firstName: userInfo.given_name,
        lastName: userInfo.family_name,
        picture: userInfo.picture,
      });
    }
  };
  getUser();
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        <div className="flex min-h-[100vh] bg-black">
          <Sidebar />
          <main className="bg-darkGrey flex-grow flex max-w-[calc(100%-250px)]">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
